if(DEFINED FUSION_CMAKE_)
    return()
else()
    set(FUSION_CMAKE_ 1)
endif()

set(FUSION_ROOT_DIR ${PROJECT_SOURCE_DIR})
message("FUSION_ROOT_DIR=${FUSION_ROOT_DIR}")
set(FUSION_CMAKE_DIR ${PROJECT_SOURCE_DIR}/cmake)
message("FUSION_CMAKE_DIR=${FUSION_CMAKE_DIR}")

include(Common/Common)
include(Platforms/Platforms)

set(FUSION_BUILD_DIR "${FUSION_BUILD_DIR}/${FUSION_SYSTEM_NAME}")
set(FUSION_BUILD_DIR "${FUSION_BUILD_DIR}-${FUSION_BUILD_ARCH}")
if(NOT "${FUSION_BUILD_VARIANT}" STREQUAL "")
    set(FUSION_BUILD_DIR "${FUSION_BUILD_DIR}-${FUSION_BUILD_VARIANT}")
endif()
set(FUSION_BUILD_DIR "${FUSION_BUILD_DIR}-${FUSION_COMPILER_NAME}")

if(NOT EXISTS FUSION_BUILD_DIR)
    file(MAKE_DIRECTORY ${FUSION_BUILD_DIR})
endif()

# Set the output directory for all of the generated artifacts
# by the build pipeline.
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${FUSION_BUILD_DIR}/lib)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${FUSION_BUILD_DIR}/obj)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${FUSION_BUILD_DIR}/bin)
